#!/bin/bash
#Xrhsimopoioume to -perm gia na vroume ta files me permissions idia me ayta pou dothikan


run=1
sum=0, sum2=0, sum3=0, sum4=0, sum5=0
while [ $run == 1 ]
do 
	echo Erwthsh1 ":" Give directory name #Zhtame onoma tou directory gia na emfanisoume ta arxeia tou
	read name #Apothikeush sthn metavlhth name
	
	VAR1=$(find /$name/ -type f | wc -l) #Vriskoume kai metrame to plhthos twn arxeiwn tou directory.
	echo "Number of files in" $name "is:" $VAR1
	sum=$(($sum+VAR1)) #Vriskoume to athroisma tou plhthous twn arxeiwn
	echo $sum
	find /$name/ -perm $1
 
	
	echo Erwthsh2 ":" Do you want to display files that changed?
	read ans
	if [ "$ans" = "yes" ]
	then
		VAR2=$(find /$name/ -type f | find . -mtime -$2 -print | wc -l) #Me thn deyterh entolh find vriskoume ta arxeia pou allaksan periexomeno tis $2 meres. Opou $2 h deyterh timh pou dinoume		
		echo "Number of files in" $name "is:" $VAR2
		echo The "sum" of these files is":"
		sum2=$(($sum2+VAR2)) #Ypologizoume to athroisma twn files ths Erwthshs 2	
		echo $sum2
		find /$name/ -type f | find . -mtime -$2 -print #Emfanizoume ta arxeia
	fi

	echo Erwthsh3 ":" Do you want to display files that accessed?
	read ans
	if [ "$ans" = "yes" ]
	then
		VAR3=$(find /$name/ -atime -$2 -type d | wc -l) #Me thn deyterh entolh find vriskoume ta direcories pou allaksan periexomeno tis $2 meres. Opou $2 h deyterh timh pou dinoume		
		echo "Number of directories in" $name "is:" $VAR3
		echo The "sum" of the files "in" $name is":"
		sum3=$(($sum3+VAR2)) #Ypologizoume to athroisma 	
		echo $sum3
		find /$name/ -maxdepth 2 -atime -$2 -type d #Emfanizoume ta directories. Psaxnoume se vathos 2
	fi


	echo Erwthsh4":" Do you want to display pipe and socket files? 
	read ans
	if [ "$ans" = "yes" ]
	then
		VAR4=$(find /$name/ -type p -or -type s | wc -l) #Me to p vriskoume ta named pipe files kai me to s ta socket files 
		echo "Number of files in" $name "is:" $VAR4
		echo The "sum" of these files is":"
		sum4=$(($sum4+VAR4)) #Ypologizoume to athroisma 	
		echo $sum4
		find /$name/ -type p -or -type s
	fi

	echo Erwthsh5":" Do you want to display empty files? 
	read ans
	if [ "$ans" = "yes" ]
	then
		VAR5=$(find /$name/ -type f -empty | wc -l) #Me to -empty vriskoume ta kena arxeia
		echo "Number of files in" $name "is:" $VAR5
		echo The "sum" of these files is":"
		sum5=$(($sum5+VAR5)) #Ypologizoume to athroisma 	
		echo $sum5
		find /$name/ -type f -empty
	fi



	echo "CONTINUE?" #Epanalamvanoume thn ektelesh tou script analoga me thn eisodo tou xrhsth
	read run #Ama dwsei kati allo ektos apo 1 h ektelesh stamataei
done
